"""Instantiate data files as Python variables."""
from pathlib import Path
import pprint
import yaml

def find_git_root(path: Path) -> Path:
    """Find the root directory of the git repository containing the given path."""
    path = path.resolve()
    if path.is_file():
        path = path.parent
    for directory in [path, *path.parents]:
        if (directory / ".git").is_dir():
            return directory
    raise FileNotFoundError(f"Could not find .git directory from {path}")


def path_relative_to_git_dir(path: Path) -> Path:
    """Return the given path relative to the git root directory."""
    return path.resolve().relative_to(find_git_root(path))


def midi_constants():
    """Generate midi_tools/constants.py with MIDI program and percussion names from YAML data."""
    with open('data/midi-programs.yaml', 'r') as fileh:
        loaded_programs = yaml.safe_load(fileh)

    programs = {
        int(key) - 1: value
        for key, value in loaded_programs.items()
    }

    with open('data/midi-percussion.yaml', 'r') as fileh:
        loaded_percussion = yaml.safe_load(fileh)

    # Unlike the program table, these keys are already raw MIDI note numbers.
    percussion = {
        int(key): value
        for key, value in loaded_percussion.items()
    }

    with open('midi_tools/constants.py', 'w') as out:
        out.write(f'''# Generated by {path_relative_to_git_dir(Path(__file__))}.\n''')
        out.write('MIDI_PROGRAMS = ')
        pprint.pp(programs, stream=out)
        out.write('\nMIDI_PERCUSSION = ')
        pprint.pp(percussion, stream=out)

def main():
    midi_constants()

if __name__ == "__main__":
    main()
